version: '3'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab.example
    container_name: gitlab.example
    ports:
      - "8080:80"
      - "8022:22"
    restart: always
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - "./gitlab/data/config:/etc/gitlab:Z"
      - "./gitlab/data/logs:/var/log/gitlab:Z"
      - "./gitlab/data/data:/var/opt/gitlab:Z"
    networks:
      gitlab_net:
        ipv4_address: 192.168.80.2

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    hostname: gitlab-runner.example
    container_name: gitlab-runner.example
    volumes:
     - './gitlab-runner/config:/etc/gitlab-runner'
     - '/var/run/docker.sock:/var/run/docker.sock'
    restart: always
    environment:
      TZ: "Asia/Tokyo"
    depends_on:
      - gitlab
    networks:
      gitlab_net:
        ipv4_address: 192.168.80.3

networks:
  gitlab_net:
    ipam:
     config:
       - subnet: 192.168.80.0/24

